version: "3.7"

services:
  api:
    container_name: websockets-jet-game
    image: api-websockets-jet-game:1.0.0
    environment:
      - HOST=db
      - PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=jetgameofthree
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["npm", "run", "start"]
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db: